image: java:latest

before_script:
  - echo nothing

stages:
  - build

build:
  stage: build
  script: 
    - ant clean
    - ant installer
  artifacts:
    name: "ttt-windows-$CI_COMMIT_SHORT_SHA"
    paths:
    - installer.exe
  artifacts:
    name: "ttt-linux-$CI_COMMIT_SHORT_SHA"
    paths:
    - ttt.zip
